version: "3.9"

services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/log/letsencrypt/:/var/log/letsencrypt/
    command: certificates
