version: "3.9"

services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes: 
      - ~/Projects/blog/static-hosting/certbot/conf:/etc/letsencrypt
      - ~/Projects/blog/static-hosting/certbot/www:/var/www/certbot
    command: certonly --non-interactive --webroot -w /var/www/certbot --force-renewal ${ACME_EMAIL} ${ACME_DOMAINS} --agree-tos
