version: "3.9"

networks:
  app-tier:

services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - ./minio/data:/data
    networks:
      - app-tier
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/custom-conf:/etc/nginx/custom-conf/
      - ./certbot/www/marco.busacchi.com:/var/www/certbot/marco.busacchi.com
      - ./certbot/www/test.timebite.net:/var/www/certbot/test.timebite.net
      - ./self-signed/certs/:/etc/ssl/certs/
      - ./self-signed/private/:/etc/ssl/private/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-tier
    restart: unless-stopped
    depends_on:
      - minio
