version: "3.9"

networks:
  app-tier:

services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - ~/Projects/blog/static-hosting/minio/data:/data
    networks:
      - app-tier
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Projects/blog/static-hosting/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ~/Projects/blog/static-hosting/nginx/conf/custom-conf:/etc/nginx/custom-conf/
      - ~/Projects/blog/static-hosting/nginx/www:/var/www/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-tier
    restart: unless-stopped
    depends_on:
      - minio
