- hosts: all

  tasks:
    - name: "ping all"
      ping:

    - name: "execute a shell command"
      shell: "date; whoami; df -h;"
      register: shell_result

    - debug:
        var: shell_result.stdout_lines
